# -*- coding: utf-8 -*-
"""Cyber

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14cjXXXb9vgVswq9ye79su9L5FvYt7Lgo
"""

!pip install cryptography

from cryptography.fernet import Fernet

key = Fernet.generate_key()
key

#Encryption

fernet = Fernet(key)

with open('key.key', 'wb') as filekey:
    filekey.write(key)

#reading
with open('key.key', 'rb') as filekey:
    key = filekey.read()

#read the file
with open('Birds chirp.mp3', 'rb') as file:
    orignal_file = file.read()

encrypted = fernet.encrypt(orignal_file)

with open('Birds chirp.mp3', 'wb') as file:
    file.write(encrypted)

# Decryting the Audio
fernet = Fernet(key)

with open('Birds chirp.mp3', 'rb') as file:
    encrypted_file = file.read()

decrypted = fernet.decrypt(encrypted_file)

with open('Birds chirp', 'wb') as file:
    file.write(decrypted)

from google.colab import drive
drive.mount('/content/drive')